# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.luks.devices.crypted.device = "/dev/disk/by-uuid/4f66e325-a9fc-4c1a-8ac1-8e425fe125c0";
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernel.sysctl = {
    "vm.swappiness" = 99;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f6f82b66-c89a-40a0-83c6-923cc95753e7";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/crypted";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B64-9AC7";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/0fc371fc-423b-4cc7-82c0-29e4bd54be56";

    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
